### ISSUE TITLE
unknown card type

### ISSUE THREAD

**Issue by netzadel** [grundid/nfctools#10]
Hello, 

I got an ACR122 NFC reader and an Android 2.3.3 Cyano modfied Samrtphone (Nexus S). After downloading the nfctools-examples-1.0-SNAPSHOT-jar-with-dependencies.jar package, i executed it with the following command:

 java -cp nfctools-examples-1.0-SNAPSHOT-jar-with-dependencies.jar org.nfctools.examples.llcp.LlcpService

The following returned on the console:

INFO : org.nfctools.examples.llcp.LlcpService - Connected to ACS ACR122 0
INFO : org.nfctools.spi.acs.AcsTerminal - Waiting...
INFO : org.nfctools.utils.LoggingStatusListener - Status: WAITING

And then an exception:

org.nfctools.mf.MfException: unknown card type: 0031C173C84000009000
        at org.nfctools.spi.acs.CardResolver.resolvecard(CardResolver.java:44)
        at org.nfctools.spi.acs.AcsTerminal.handleMfCard(AcsTerminal.java:104)
        at org.nfctools.spi.acs.AcsTerminal.initInitiatorDep(AcsTerminal.java:67)
        at org.nfctools.examples.llcp.LlcpService.run(LlcpService.java:86)
        at org.nfctools.examples.llcp.LlcpService.main(LlcpService.java:97)

could you help me with this? 

thank you for your great work!

Best regards! 
Berry

**Comment by grundid** [comment]
This is quite old stuff ;) Do you use the "My Tag" app or something?

I don't think I can add support for this. There is no info how to communicate with this app.

**Comment by netzadel** [comment]
No id dont use any app. Iam a novice in this case :) could you explain in a few words what i need to send a simple tag over a peer2peer connection to my Nexus S?

**Comment by grundid** [comment]
Please update to Android 4.0.4 first. 
Then you can use my NDEF Applet Demo (http://www.grundid.de/nfc) to transfer data.

**Comment by netzadel** [comment]
To be honest iam absolutely new to nfc. I buyd an ACR122U and took my Nexus S to test NFC. So i thought i could easily create a little java tool, to receive a tag sent by my smartphone... but i failed completely :D at first i tried the javax.smartcardIo package to communicate with the reader. That worked well but i couldn establish a P2P connection. Then i found your site, and your java applet. I watched your video and tried to recreate your steps. But i failed again. Despite i used IE64bit Java6 nothing happened. So i decided to code my own little tool again... and to be honest again, i have no clue how to start. The aim is to receive a tag sendet by the Nexus (2.3.3) over p2p. could you spare a little tip for me :D this would be awsome!

**Comment by netzadel** [comment]
Ok, the android version seems to be my problem. I simply cant update to 4.0.4 :( because i didn´t received a update information from google... is there a way to get 4.0.4 and install it manually? by the way: thanks for your time! i allready spent 3 days to achieve that task.. you are my hero :D

**Comment by grundid** [comment]
It's great that you're working with NFC :)

As for the nfctools, I'm sorry, but you have to update your Nexus S first. There are some changes in Android since version 4.x and I this library only works with the newer version.

**Comment by netzadel** [comment]
Ok i found a way to manually upgrade my Nexus. I will work on that and hopefully will get nfc working :D thank you so much!

**Comment by grundid** [comment]
Ok, great. 
Give me a hit if it is working for you with the new version ;)

**Comment by netzadel** [comment]
Yes i will :) was it possbile to send Tags via P2P mode from an android device before android beam?

**Comment by grundid** [comment]
Yes, it works with Ndef Push Protocol (NPP) and you can implement your own solution.

**Comment by netzadel** [comment]
oh that sounds greate. i know i demand much.. but could you give me some hints or sites where i can gather more information how to establish a connection with NPP in java?

**Comment by grundid** [comment]
Not in java, but you can try python:
https://launchpad.net/nfcpy

**Comment by netzadel** [comment]
Thank you very very much for your help, i will try both ways asap and let you know which way worked well for me. Thanks again!

**Comment by netzadel** [comment]
Hey its me again :D i updated now successfully to 4.0.4 and let me tell you, your app is working wonderful :D good job! ok, but now a have a little prob. I just want to receive a text from my Nexus S over the ACR122. Sending this tab via Android Beam isnt a problem, but receiving. I created an Tag writing app, now i need some application on the desktop side. This app should just wait for a tag and write it into a textbox or something. Could you give me a little tip? thank you!

**Comment by grundid** [comment]
I'm glad it is working now.

Have you tried the above LlcpService? This app writes everything on the screen. You can replace the logger and write the data into your own textbox.

**Comment by netzadel** [comment]
Hey, thanks for the fast response.
Yes is did, and it looked a lot better then yesterday. But i received an error after sending a playin text with TagWriterApp:

DEBUG: org.nfctools.spi.acs.ApduReaderWriter - response APDU <=
org.nfctools.spi.acs.ApduException: Error sending message [D440010000](0,5) =>
[]
        at org.nfctools.spi.acs.ApduReaderWriter.write(ApduReaderWriter.java:110
)
        at org.nfctools.spi.tama.AbstractTamaCommunicator.sendMessageInternal(Ab
stractTamaCommunicator.java:62)
        at org.nfctools.spi.tama.AbstractTamaCommunicator.sendMessage(AbstractTa
maCommunicator.java:51)
        at org.nfctools.spi.tama.nfcip.InitiatorNfcIpConnection.send(InitiatorNf
cIpConnection.java:85)
        at org.nfctools.llcp.LlcpOverNfcip.onConnection(LlcpOverNfcip.java:45)
        at org.nfctools.scio.AbstractTerminal.handleNfcipConnection(AbstractTerm
inal.java:66)
        at org.nfctools.spi.acs.AcsTerminal.openLlcpStack(AcsTerminal.java:120)
        at org.nfctools.spi.acs.AcsTerminal.initInitiatorDep(AcsTerminal.java:64
)
        at org.nfctools.examples.llcp.LlcpService.run(LlcpService.java:86)
        at org.nfctools.examples.llcp.LlcpService.main(LlcpService.java:97)
INFO : org.nfctools.utils.LoggingStatusListener - Status: DISCONNECTED

i think this is what you meant with old stuff :D with what app or tool should i write a tag? are there any suggestions from your part?

thanks a lot

**Comment by netzadel** [comment]
Hi, its me again :D finally it seems to work even in my java build. after reading a tag from my androif, the log added the folliwing line:

DEBUG: org.nfctools.spi.acs.ApduReaderWriter - response APDU <= D541008320000100000001010000006F91013E55036D61726B65742E616E64726F69642E636F6D2F7365617263683F713D706E616D653A636F6D2E6E6663717569636B616374696F6E732E61707066726565540F1B616E64726F69642E636F6D3A706B67636F6D2E6E6663717569636B616374696F6E732E61707066726565
INFO : org.nfctools.utils.LoggingNdefListener - Uri: [http://market.android.com/search?q=pname:com.nfcquickactions.appfree]
INFO : org.nfctools.utils.LoggingNdefListener - Namespace: [android.com:pkg] Content: [com.nfcquickactions.appfree]

i sent a plain text, but it seems to be encrypted or something, the text i sent was "test". is it possible to only add "test" to an textbox?   if this works, i could sent you the "Android Tag" app i wrote. thanks again!

**Comment by grundid** [comment]
What you see here is a standard Android Beam message. This message is send by Android itself and it is simply the URL to the Andoird Market aka Google Play.

I don't know if the app NFC Quick Actions is capable of P2P. It usually only writes on NFC tags.

I'll close this issue since it is no longer nfctools related.
Please join the nfc-developers group if you want to discuss NFC development in general.
https://groups.google.com/forum/?hl=de&fromgroups#!forum/nfc-developers
