### ISSUE TITLE
[Nexus 7 JB4.2) Android Beam problem

### ISSUE THREAD

**Issue by jefBinomed** [grundid/nfctools#14]
Hello i have a problem for sending ndef message to the nfc card I have with my Nexus 7
Here is my configuration : 

Nexus 7 with Jelly Bean 4.2.1
Card ACS => ACR122 U-A9

I just do simple beam message with android.

What is strange is when I'm using the same application but with my nexus 4 it works, I could send the message to the card.

The behaviour i observe is  : I see the "beam screen" from android but when i tap on the screen, nothing appends...

What do I missed ?

Here is the log I have : 

DEBUG: org.nfctools.spi.acs.AcsDirectChannelTag - response: D58D251ED400CE4389C53B8BE69F03C20000003246666D010111030200130401969000
DEBUG: org.nfctools.spi.acs.AcsDirectChannelTag - command: FF00000002D486
DEBUG: org.nfctools.spi.acs.AcsDirectChannelTag - response: D5870000009000
DEBUG: org.nfctools.ndefpush.NdefPushLlcpService - 0 NDEF messages to send
DEBUG: org.nfctools.spi.acs.AcsDirectChannelTag - command: FF00000004D48E0000
DEBUG: org.nfctools.spi.acs.AcsDirectChannelTag - response: D58F009000
DEBUG: org.nfctools.spi.acs.AcsDirectChannelTag - command: FF00000002D486
DEBUG: org.nfctools.spi.acs.AcsDirectChannelTag - response: D5870000009000
DEBUG: org.nfctools.ndefpush.NdefPushLlcpService - 0 NDEF messages to send
...
org.nfctools.spi.tama.TamaException: 0x29: The PN531 configured as a target has been released by its initiator
    at org.nfctools.spi.tama.TamaUtils.handleStatusCode(TamaUtils.java:22)
    at org.nfctools.spi.tama.response.TamaResponseDecoder.handleStatusCode(TamaResponseDecoder.java:76)
    at org.nfctools.spi.tama.response.TamaResponseDecoder.createGetDepDataResp(TamaResponseDecoder.java:117)
    at org.nfctools.spi.tama.response.TamaResponseDecoder.decodeMessage(TamaResponseDecoder.java:48)
    at org.nfctools.spi.tama.AbstractTamaCommunicator.sendMessage(AbstractTamaCommunicator.java:54)
    at org.nfctools.spi.tama.nfcip.TargetNfcIpConnection.receive(TargetNfcIpConnection.java:46)
    at org.nfctools.llcp.LlcpOverNfcip.onConnection(LlcpOverNfcip.java:43)
    at org.nfctools.spi.acs.AbstractTerminalTagScanner.handleNfcipConnection(AbstractTerminalTagScanner.java:83)
    at org.nfctools.spi.acs.TargetTerminalTagScanner.run(TargetTerminalTagScanner.java:55)
    at java.lang.Thread.run(Unknown Source)

**Comment by grundid** [comment]
Sorry, but I haven't figured out why this 0x29 error happens. I noticed that the message can be transfered if you try several times.

Have you tried the Initiator mode? I don't have the N7 at my disposal atm so I cannot try it myself.

**Comment by jefBinomed** [comment]
Hi thank you for your so fast answer :)

I've just try with the INITIATOR MODE and it don't even work. The card just beep and passed to red light. 

Here is the log i have : 

DEBUG: org.nfctools.spi.acs.InitiatorTerminalTagScanner - Waiting while card present
DEBUG: org.nfctools.spi.acs.InitiatorTerminalTagScanner - Wait for card absent
DEBUG: org.nfctools.spi.acs.InitiatorTerminalTagScanner - Disconnected

How can we proceed to understand why it doesn't work ? Because i haven't understand all the "magics aspect" of your libraries :)

**Comment by grundid** [comment]
I guess the magic is unfortunately hidden in a ton of PDF specs. I recommend reading all the stuff from nfc-forum.org and also how the PN532 chip in the ACR122 works (http://www.adafruit.com/datasheets/pn532um.pdf)

The 0x29 error is defined in the PN532 pdf. Maybe you can better understand how to prevent it.
Please join our nfc-developers forum linked from the readme file.
