### ISSUE TITLE
[Android application reccord] how to passed multiples records ?

### ISSUE THREAD

**Issue by jefBinomed** [grundid/nfctools#15]
Hello, i have a problem with the AndroidApplicationRecord.
# my problem

Here is what i want : I want that when i use the card as SNEP mode for my phone, the phone launch the application I've code and if the user doesn't have it, he will asked to download it. 

This kind of mecanism is that http://developer.android.com/guide/topics/connectivity/nfc/nfc.html#aar.
 I used it with my android application for beam messages but I want to do the same thing with the card. 

Here is what i do : 

I start from the class  https://github.com/grundid/nfctools-examples/blob/master/src/main/java/org/nfctools/examples/snep/SnepDemo.java and i adapt it for my needs : use 2 records ; the first is an UnsupportedExternalTypeRecord and the second is an AndroidApplicationRecord.

The problem is when i want to read the ndef message from the phone, nothing appends. I heard the beam sound which means that something is trying to append but on the java program, i have this exception : 

> org.nfctools.spi.tama.TamaException: 0x29: The PN531 configured as a target has been released by its initiator
>   at org.nfctools.spi.tama.TamaUtils.handleStatusCode(TamaUtils.java:22)
>   at >org.nfctools.spi.tama.response.TamaResponseDecoder.handleStatusCode(TamaResponseDecoder.java:76)
>   at >org.nfctools.spi.tama.response.TamaResponseDecoder.createGetDepDataResp(TamaResponseDecoder.java:117)
>   at >org.nfctools.spi.tama.response.TamaResponseDecoder.decodeMessage(TamaResponseDecoder.java:48)
>   at >org.nfctools.spi.tama.AbstractTamaCommunicator.sendMessage(AbstractTamaCommunicator.java:54)
>   at org.nfctools.spi.tama.nfcip.TargetNfcIpConnection.receive(TargetNfcIpConnection.java:46)
>   at org.nfctools.llcp.LlcpOverNfcip.onConnection(LlcpOverNfcip.java:43)
>   at >org.nfctools.spi.acs.AbstractTerminalTagScanner.handleNfcipConnection(AbstractTerminalTagScanner.java:83)
>   at org.nfctools.spi.acs.TargetTerminalTagScanner.run(TargetTerminalTagScanner.java:55)
>   at java.lang.Thread.run(Unknown Source)

I know how to intercept just my UnsupportedExternalTypeRecord with the filters but I want to have the android mecanism that search on the market the application according to the package name.

here is a little tab of what works for me

<table>
<tr>
<td>Action</td>
<td>Nexus 7</td>
<td>Nexus 4</td>
</tr>
<tr>
<td>Send a simple AndroidApplicationRecord</td>
<td>KO</td>
<td>OK</td>
</tr>
<tr>
<td>Send an UnsupportedExtarnaltTypeRecord and catch him by the application</td>
<td>OK</td>
<td>OK</td>
</tr>
<tr>
<td>Send a simple AndroidApplicationRecord and an UnsupportedExtternalTypeRecord when the application is not installed</td>
<td>KO</td>
<td>KO</td>
</tr>
</table>

# my configuration
- Nexus 7 JellyBean 4.2.1
- Nexus 4 JellyBean 4.2.1
- ACS ACR122U-A9

**Comment by grundid** [comment]
Could you please explain what you mean by "use the card as SNEP mode". If you are referring to card emulation, then this won't work with nfctools. At least I haven't figured out how to do that.

Otherwise it looks more like an Android problem. Please notice that the N7 and N4 have different NFC chips. It is already known that they act a little bit different.

**Comment by jefBinomed** [comment]
By "SNEP Mode" I mean I want to use the card to communicate informations to the phone. As if the card is a simple nfc tag.

**Comment by grundid** [comment]
Well ok. I guess by card you mean the desktop reader. ;)

How do you create the NDEF messages? Do you create two NDEF messages or one NDEF message with two records?

**Comment by jefBinomed** [comment]
Here is my code 

```
    /**
 * @param args
 */
public static void main(String[] args) {

    // Init ACS
    LoggingNdefListener loggingNdefListener = new LoggingNdefListener();
    SnepServer snepServer = new SnepServer(loggingNdefListener);
    SnepClient snepClient = new SnepClient();
    LlcpOverNfcip llcpOverNfcip = new LlcpOverNfcip();
    LlcpConnectionManager connectionManager = llcpOverNfcip.getConnectionManager();
    connectionManager.registerServiceAccessPoint(SnepConstants.SNEP_SERVICE_ADDRESS, snepServer);
    connectionManager.registerServiceAccessPoint(snepClient);

    // Specify Data to send
    snepClient.setSnepAgentListener(new CallBackWrite(-1, ""));

    // Run the reception
    TerminalMode terminalMode = TerminalMode.TARGET;
    TerminalHandler terminalHandler = new TerminalHandler();
    terminalHandler.addTerminal(new AcsTerminal());
    Terminal terminal = terminalHandler.getAvailableTerminal();
    System.out.println("Using: " + terminal.getTerminalName());
    NfcAdapter nfcAdapter = new NfcAdapter(terminal, terminalMode);
    nfcAdapter.setNfcipConnectionListener(llcpOverNfcip);
    nfcAdapter.startListening();
    System.out.println("Mode: " + terminalMode);
    System.out.println("Waiting for P2P, press ENTER to exit");
    try {
        System.in.read();
    } catch (IOException e) {
        e.printStackTrace();
    }

}

static class CallBackWrite implements SnepAgentListener, PutResponseListener {

    private List<Record> records = new ArrayList<Record>();

    public CallBackWrite(int type, String... data) {


        records.add(new UnsupportedExternalTypeRecord("com.binomed.sqli:market_customer", "1"));
        records.add(new AndroidApplicationRecord("com.binomed.sqli.nfc"));


    }

    public void onSnepConnection(SnepAgent snepAgent) {
        if (!records.isEmpty()) {
            System.out.println("SNEP connection available, sending message...");
            snepAgent.doPut(new ArrayList<Record>(records), this);
            records.clear();
        }
    }

    public boolean hasDataToSend() {
        return !records.isEmpty();
    }

    public void onSuccess() {
        System.out.println("SNEP succeeded");
        records.clear();
    }

    public void onFailed() {
        System.out.println("SNEP failed");
    }

}
```

**Comment by grundid** [comment]
It looks ok. But why don't you send an MimeType record? Maybe android doesn't like UnsupportedExternalTypeRecords ;)

**Comment by jefBinomed** [comment]
It finally works, but i don't understand what I do... One times it works... I think the problem comes from my comprehension of TARGET and INITIATOR modes
