### ISSUE TITLE
IOCTLs for the SCL3711

### ISSUE THREAD

**Issue by mauimauer** [grundid/nfctools#6]
Hi there,

I have just started out fiddling around with nfctools (great work, btw) and I wondered what the source of the mentioned IOCTLs of the SCL3711 is. The manual available on SCMs Homepage only lists 0x900 (getCardType).

Especially since target-mode is not implemented yet I would really plike to help out here.

Greetings,
maui

**Comment by grundid** [comment]
Hi Maui,

SCM offers a document with the title "Application Note AN0003 NFC P2P with SCL3711". I got it from the support stuff. Since it is publicly available I can send it to you if you give me your e-mail address.

Please note that version 1.0 of the doc has a typo with IOCTL 0x906 which is used twice. I have corrected it in the "Scl3711" class.

Regards,
Adrian.

**Comment by mauimauer** [comment]
Hi Adrian,

I started to implement MfReader and Target Mode for the SCL3711. I am testing my implementation with the LLcpService example and my trusty Galaxy Nexus.

`04-20 17:56:21.591: D/NFC JNI(639): Discovered P2P Target
04-20 17:56:21.591: D/NfcService(639): LLCP Activation message
04-20 17:56:21.622: I/NFC JNI(639): LLCP Link activated (LTO=10, MIU=128, OPTION=0x00, WKS=0x01)
04-20 17:56:21.622: I/NfcP2pLinkManager(639): LLCP activated
04-20 17:56:21.622: D/NfcP2pLinkManager(639): onP2pInRange()
04-20 17:56:21.896: D/NfcP2pLinkManager(639): onP2pSendConfirmationRequested()
04-20 17:56:22.474: I/NFC JNI(639): LLCP Link deactivated
04-20 17:56:22.482: D/NfcService(639): LLCP Link Deactivated message. Restart polling loop.
04-20 17:56:22.482: I/NfcP2pLinkManager(639): LLCP deactivated.
04-20 17:56:23.232: D/NfcP2pLinkManager(639): Debounce timeout
04-20 17:56:23.232: D/NfcP2pLinkManager(639): onP2pOutOfRange()`

So the SCL3711 is properly put into P2P target mode and is recognised by the Galaxy Nexus. Now I am facing the Problem that IOCTL_TARGET_RECEIVE always seems to respond with 0x00 0x00.

Also I am not sure wether to handle the immediate reply IOCTL_TARGET_SEND with one byte as mentioned as mandatory in the P2P Target sample. The NFCIPConnectionListener should care about responding, right?

If you want I can commit the code I have so far.

**Comment by grundid** [comment]
Please, tell me first why you need the target mode? ;) The SCL3711 works quite nice in initiator mode.

Since I haven't done any work in target mode so far, it is difficult for me to say what is wrong. 

BTW: you can always push the code into your clone. Just tell me in which branch it is.

**Comment by mauimauer** [comment]
Well...because the device is able to do it. Why not use/support that feature.
But I agree that target mode is not a critical feature because nfctools already has pretty solid initiator support.
I'll be preparing what I have so far.
